#The action of this plugin
#"change"= remove the old villager and spawn a new one at the same location
#"remove" = remove the villager anyway
action: change
#The chance of a Villager change his proffession or been removed while trade refreshs,Max 100,Default 10
chance: 10
#The message to send to nearby players while a villager changed his proffesion or been removed
#set to "" to disable
#&7<&bVillager&7> &rMan is mortal...
message: "&7<&bVillager&7> &rThis is too bored, I'm gonna change my job!" 
#wether villager changes or removes log to console
consolelogs: true
#How long should a villager at least live in order to change his proffesion or been removed, in ticks, 20 tick = 1s
#Default 36000,Do not recommand set this to 0!
ticks: 36000